# Generated by Django 4.2.7 on 2024-05-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_college_student_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_changed_password',
            field=models.BooleanField(default=False),
        ),
    ]
