# Generated by Django 4.2.7 on 2024-05-11 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_is_changed_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone',
            new_name='mobile_number',
        ),
    ]
