# Generated by Django 4.2.7 on 2024-05-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_phone_student_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='linkedin_id',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/student_profile/default.jpg', null=True, upload_to='student_profile/'),
        ),
    ]
