# Generated by Django 4.2.7 on 2024-05-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='college',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
