# Generated by Django 4.2.7 on 2024-05-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_instructor_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
