# Generated by Django 4.2.7 on 2024-05-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_instructor_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/student_profile/default.jpg', null=True, upload_to='teacher_profile'),
        ),
    ]
