# Generated by Django 4.2.7 on 2024-06-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_roadmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
