# Generated by Django 4.2.7 on 2024-05-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_anonymous_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymous_message',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
