# Generated by Django 4.2.7 on 2024-06-09 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_notification_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='course',
        ),
    ]
