# Generated by Django 4.2.7 on 2024-06-17 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_course_name'),
        ('student', '0010_assignment_assignmentsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.CharField(default='None', max_length=255)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'verbose_name': 'AI Question',
                'verbose_name_plural': 'AI Questions',
            },
        ),
    ]
