# Generated by Django 4.2.7 on 2024-06-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_assignmentsubmission_submission_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
